[project]
name = "first-ai-agent-chainlit"
version = "0.1.0"
description = "First Ai agent with chainlit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.6.0",
    "openai-agents>=0.0.17",
    "python-dotenv>=1.1.0",
]
